#!/usr/bin/env python
#Filename: ex16.py 写入文件

from sys import argv #从sys模块引入argv用于从命令行读取输入（string）
                     #另一种读取输入的方式为input函数
script , filename = argv 
#(程序名)  

print("We'are going to erase %r." %filename)
print("If you dont want that,hit CTRL-C(^C)")
print("If you donot want that,hit RETURN.")

print("Open the file...")

target = open(filename,"w")

print("Truncating the file. Goodbye!")
target.truncate()
#truncate 方法处理文件时，文件不能用只读模式！！

print("Now,I'm going to ask you for three lines.")

line1 = input("line1: ")
line2 = input("line2: ")
line3 = input("line3: ")

print("I'm going to write these to the file.")

target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")

print("And finally, We close it")
target.close()

                           



