#!usr/bin/env python
#Filename: eg.py

class Song(object):
    def __init__(self, lyrics):
        self.lyrics = lyrics

    def sing_me_a_song(self):
        for line in self.lyrics:
            print(line)

happy_bday = Song(["Happy birthday to you",
                   "i dont want to get sued",
                   "so i'll stop right there"])

bulls_one_parade = Song(["They rally around the family",
                         "with pockets full of shells"])

happy_bday.sing_me_a_song()

bulls_one_parade.sing_me_a_song()

$python3 eg.py
Happy birthday to you
i dont want to get sued
so i'll stop right there
They rally around the family
with pockets full of shells

                           



