#!/usr/bin/env python
#Filename: hanoi.py

count = 0
def hanoi(n,A,B,C):
    if n == 1:
        print("move",n,"from",A,"to",C)
    else:
        hanoi(n-1,A,C,B)
        print("move",n,"from",A,"to",C)
        hanoi(n-1,B,A,C)


n = int(input("input the amount of disks:"))
hanoi(n,'left','mid','right')


;==================================================
#Filename: parking.py

import random

def parking(low,high):
    if high - low < 1:
        return 0
    else:
        x = random.uniform(low,high-1)
        return parking(low,x) + 1 + parking(x+1,high)
m = 0
for i in rang(1000):
    m += parking(0,5)

print(1.0*m/1000)



